# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Coffee(object):
    def setupUi(self, Coffee):
        Coffee.setObjectName("Coffee")
        Coffee.resize(800, 600)
        Coffee.setMinimumSize(QtCore.QSize(800, 600))
        Coffee.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(Coffee)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.coffee_view = QtWidgets.QTableView(self.centralwidget)
        self.coffee_view.setObjectName("coffee_view")
        self.gridLayout.addWidget(self.coffee_view, 0, 0, 1, 1)
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_btn.setFont(font)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout.addWidget(self.add_btn, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        Coffee.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Coffee)
        self.statusbar.setObjectName("statusbar")
        Coffee.setStatusBar(self.statusbar)

        self.retranslateUi(Coffee)
        QtCore.QMetaObject.connectSlotsByName(Coffee)

    def retranslateUi(self, Coffee):
        _translate = QtCore.QCoreApplication.translate
        Coffee.setWindowTitle(_translate("Coffee", "Coffee"))
        self.add_btn.setText(_translate("Coffee", "Добавить информацию о новом кофе / Изменить имеющуюся."))
